name: spell-check-differential

on:
  pull_request:

jobs:
  spell-check-differential:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run spell-check
        uses: autowarefoundation/autoware-github-actions/spell-check@v1
        with:
          config_path: .spellcheck.yml # path of the configuration file
          task_name: Code
          cspell-json-url: https://raw.githubusercontent.com/tier4/autoware-spell-check-dict/main/.cspell.json
          
